config/routes.rb
Rails.application.routes.draw do
  resources :posts do
    resources :comments
  end
  root to: 'posts#index'
  
  get   'about', to: 'static_pages#about'
  get   'contact', to: 'static_pages#contact'
  get   'privacy', to: 'static_pages#privacy'
  devise_for :users
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
end

app/models/post.rb
# == Schema Information
#
# Table name: posts
#
#  id         :integer          not null, primary key
#  content    :text
#  title      :string
#  created_at :datetime         not null
#  updated_at :datetime         not null
#  user_id    :integer          not null
#
# Indexes
#
#  index_posts_on_user_id  (user_id)
#
# Foreign Keys
#
#  user_id  (user_id => users.id)
#
class Post < ApplicationRecord
  belongs_to :user
  has_many :comments, dependent: :destroy
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :set_post, only: %i[ show edit update destroy ]
  before_action :authenticate_user!, except: [:index, :show]

  # GET /posts or /posts.json
  def index
    @posts = Post.all.order(created_at: :desc).includes([:user])
  end

  # GET /posts/1 or /posts/1.json
  def show
    @comments = @post.comments.includes([:user])
  end

  # GET /posts/new
  def new
    @post = Post.new
  end

  # GET /posts/1/edit
  def edit
  end

  # POST /posts or /posts.json
  def create
    # @post = Post.new(post_params)
    @post = current_user.posts.build(post_params)

    respond_to do |format|
      if @post.save
        format.html { redirect_to post_url(@post), notice: "Post was successfully created." }
        format.json { render :show, status: :created, location: @post }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /posts/1 or /posts/1.json
  def update
    respond_to do |format|
      if @post.update(post_params)
        format.html { redirect_to post_url(@post), notice: "Post was successfully updated." }
        format.json { render :show, status: :ok, location: @post }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /posts/1 or /posts/1.json
  def destroy
    @post.destroy

    respond_to do |format|
      format.html { redirect_to posts_url, notice: "Post was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_post
      @post = Post.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def post_params
      params.require(:post).permit(:title, :content)
    end
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/posts/_form.html.haml
= simple_form_for @post do |f|
	= f.input :title
	= f.input :content
	= f.submit

app/views/posts/edit.html.haml
%h1 Edit Post

= render 'form'

= link_to "Cancel", post_path

app/views/posts/index.html.haml
#posts
	- @posts.each do |post|
		.post
			%h2.title= link_to post.title, post
			%p.date
				Published at
				= time_ago_in_words(post.created_at)
				by
				= post.user.email

app/views/posts/new.html.haml
%h1 New Post

= render 'form'

app/views/posts/show.html.haml
#post_content
	%h1= @post.title
	%p= @post.content

	#comments
		%h2
			= @comments.count
			Comments
		= render @comments

		%h3 Reply to thread
		= render "comments/form"

	%br/
	%hr/
	%br/

	= link_to "Edit", edit_post_path(@post), class: "button"
	= button_to "Delete", post_path(@post), method: :delete, data: { confirm: "Are you sure you want to do this?" }